#!/bin/sh

LOG=$(git log -1 -p)
# get first 8 bytes of revision from git log
REV=$( echo "$LOG" | head -1 | cut -d' ' -f 2 | cut -c -8)
#diff --git a/src/routes/drawing/sttest/+page.svelte b/src/routes/drawing/sttest/+page.svelte

# look for diff in src/routes/drawing
DIFFLINE_WITH_DRAWING=$( echo "$LOG" | grep diff | grep "src/routes/drawing")

if [[ -n "$DIFFLINE_WITH_DRAWING" ]]; then
  # get drawing name from a/src/routes/drawing/here
  NAME=$(echo "$DIFFLINE_WITH_DRAWING" | cut -d'/' -f 5)
  TIME=$(date +%s)
  echo "You changed '$NAME' at $TIME revision $REV"
  if [ ! -d "static/history/$NAME" ]; then
    mkdir -p "static/history/$NAME"
  fi
  cp static/drawings/svg/$NAME.svg static/history/$NAME/$NAME.$TIME.$REV.svg
fi

